import Head from 'next/head'
import Header from '../components/Header'

import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <Header />
      <Component {...pageProps} />
    </div>
  )
}

export default MyApp
